engines:
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 20
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
    - app/**/*
    - lib/**/*
exclude_paths: # customize
- .bundle/
- doc/
- spec/
- tmp/

